# Generated by Django 4.1.2 on 2022-11-29 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payfast',
            old_name='email_address',
            new_name='amount_fee',
        ),
        migrations.RenameField(
            model_name='payfast',
            old_name='phoneNumber',
            new_name='amount_gross',
        ),
        migrations.RenameField(
            model_name='payfast',
            old_name='tax_number',
            new_name='amount_net',
        ),
        migrations.RenameField(
            model_name='payfast',
            old_name='address_line',
            new_name='m_payment_id',
        ),
        migrations.RenameField(
            model_name='payfast',
            old_name='postal_code',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='payfast',
            old_name='customer_name',
            new_name='pf_payment_id',
        ),
        migrations.AddField(
            model_name='payfast',
            name='billing_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='payfast',
            name='item_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payfast',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payfast',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payfast',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
