# Generated by Django 4.1.2 on 2022-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_email_address_payfast_amount_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payfast',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
