# Generated by Django 4.1.2 on 2022-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
