# Generated by Django 4.1.2 on 2022-11-04 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0002_tenant_address_tenant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
