# Generated by Django 4.1.2 on 2022-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0004_terms_status_provinces_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Flag weather the user has paid or not.', verbose_name='has paid'),
        ),
    ]
