# Generated by Django 4.1.2 on 2022-12-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0006_alter_customuser_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Flag weather the user has paid or not.'),
        ),
    ]
