# Generated by Django 4.1.2 on 2022-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0008_alter_customuser_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='free_invoice',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
