# Generated by Django 4.1.2 on 2022-12-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0009_tenant_free_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
