# Generated by Django 4.1.2 on 2022-12-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0010_tenant_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='company_logo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='tenant',
            name='image_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
