# Generated by Django 4.1.2 on 2023-01-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0013_alter_tenant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
