# Generated by Django 4.1.2 on 2023-02-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0014_alter_tenant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='system_management.currency'),
        ),
    ]
