# Generated by Django 4.1.2 on 2023-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0015_tenant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
