# Generated by Django 4.1.2 on 2023-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0016_currency_code_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bank_account_holder',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_account_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
