# Generated by Django 4.1.2 on 2022-11-05 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_management', '0004_terms_status_provinces_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system_management.tenantawaremodel')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='system_management.provinces')),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
            bases=('system_management.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system_management.tenantawaremodel')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.customer')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='system_management.status')),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='system_management.terms')),
            ],
            bases=('system_management.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system_management.tenantawaremodel')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='system_management.currency')),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('system_management.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system_management.tenantawaremodel')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('invoices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.invoice')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='business.product')),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('system_management.tenantawaremodel',),
        ),
    ]
