# Generated by Django 4.1.2 on 2022-11-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_invoicedetail_banking_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='banking_details',
        ),
        migrations.AddField(
            model_name='invoice',
            name='banking_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='business.bankingdetails'),
        ),
    ]
