# Generated by Django 4.1.2 on 2022-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_invoice_free_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_data',
            field=models.JSONField(default={}),
        ),
    ]
