# Generated by Django 4.1.2 on 2022-12-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_invoice_invoice_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='free_invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
    ]
