# Generated by Django 4.1.2 on 2022-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_invoice_free_invoice_delete_invoicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
