# Generated by Django 4.1.2 on 2022-11-05 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_management', '0004_terms_status_provinces_currency'),
        ('invoice', '0002_alter_invoice_options_alter_invoicedetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='system_management.tenantawaremodel')),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BankingDetails',
            },
            bases=('system_management.tenantawaremodel',),
        ),
    ]
