# Generated by Django 4.1.2 on 2022-11-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_bankingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='banking_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invoice.bankingdetails'),
        ),
    ]
