# Generated by Django 4.1.2 on 2022-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_invoicedetail_banking_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='free_invoice',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
