# Generated by Django 4.1.2 on 2023-02-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='has_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
