# Generated by Django 4.1.2 on 2024-02-22 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0012_invoice_has_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="view_dates",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
