name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      #WEBSITE_HOSTNAME : ${{ secrets.WEBSITE_HOSTNAME }}

      SANDBOX_MODE: ${{ secrets.SANDBOX_MODE }}
      MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
      MERCHANT_KEY: ${{ secrets.MERCHANT_KEY }}
      PASS_PHRASE: ${{ secrets.PASS_PHRASE }}
      CART_TOTAL: ${{ secrets.CART_TOTAL }}

      EMAIL_HOST_NAME: ${{ secrets.EMAIL_HOST_NAME }}
      EMAIL_HOST_PORT: ${{ secrets.EMAIL_HOST_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
